### ISSUE TITLE
Correct "Singup" Typo to "Signup" Throughout Codebase

### ISSUE THREAD

**Issue by kunxl-gg** [LainForge/Neura-Launch-Dashboard#11]
- There is a function called *Singup* which should be named Signup. Correct the typo at all the places in the codebase

**Comment by nishantdub37** [comment]
@kunxl-gg can you assign this issue to me?

**Comment by rohansingh9001** [comment]
Sure @nishantdub37 take it up.

The function is question is in `dashboard/controllers/authController.go`

It is also used only at one place in main.go.

Its a basic typo in both these locations.

**Comment by kunxl-gg** [comment]
sure @nishantdub37 go ahead
