### ISSUE TITLE
Add Issue Template

### ISSUE THREAD

**Issue by kunxl-gg** [LainForge/Neura-Launch-Dashboard#13]
## Description 
We do not have any issue templates. We would like to have a few issue templates, one for bugs and another for feature requests. You are open to suggest templates for other purposes as well.

## Possible Fix/Solution
Make an issue_template.md file the .github folder of this project. You can refer to this [link](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) for any further information.

**Comment by engineerakki** [comment]
I can work on this if needed.
Can you assign it to me ?

**Comment by nishantdub37** [comment]
@kunxl-gg can i do this?
