### ISSUE TITLE
Add CI in GitHub Actions

### ISSUE THREAD

**Issue by engineerakki** [LainForge/Neura-Launch-Dashboard#17]
### Is your proposal related to a problem?

It would be great if we could have CI in GitHub Actions,

### Describe the solution you'd like

- Add GitHub Actions CI for Go code (Lint and Compile Go Code in GitHub Actions if  files changed in client directory )
- Add GitHub Actions CI for React Code (Lint and Compile JS Code in GitHub Actions if  files changed in dashboard directory )
- Fail the GitHub Action if compile and lint are not successful.

### Requirement/Document

None

**Comment by engineerakki** [comment]
I can take this if it is relevent

**Comment by rohansingh9001** [comment]
Can you describe the scope and solutions that you have in mind?

**Comment by engineerakki** [comment]
> Can you describe the scope and solutions that you have in mind?

- Add GitHub Actions CI for Go code (Lint and Compile Go Code in GitHub Actions if  files changed in client directory )
- Add GitHub Actions CI for React Code (Lint and Compile JS Code in GitHub Actions if  files changed in dashboard directory )
- Fail the GitHub Action if compile and lint are not successful.

**Comment by rohansingh9001** [comment]
sure go ahead.

**Comment by TarunTomar122** [comment]
pr - #18
