### ISSUE TITLE
CI: add a Github workflow CI for builder service

### ISSUE THREAD

**Issue by TarunTomar122** [LainForge/Neura-Launch-Dashboard#23]
### Problem Context
We have a GitHub workflow for both the client and dashboard right now. However, there's no CI for builder service (since it was recently introduced into the project). 

### Solution

So we basically want a new GitHub workflow (very similar to the existing one for the dashboard) that should run on updating builder service code to verify if the code and docker image can be built successfully.

Note: Check out [this](https://github.com/LainForge/Neura-Launch-Dashboard/blob/main/.github/workflows/ci-dashboard.yml) file for reference.

**Comment by engineerakki** [comment]
I can add this workflow.
